### ISSUE TITLE
Development dependencies included in nuspec / published nuget package

### ISSUE THREAD

**Issue by CZEMacLeod** [pierresprim/IconLib#2]
The following is in the nuspec file causing the development dependencies to be required by the published package.
```
      <dependency id="Microsoft.Build.Tasks.Git" version="1.0.0-beta2-19367-01" />
      <dependency id="Microsoft.SourceLink.Common" version="1.0.0-beta2-19367-01" />
      <dependency id="Microsoft.SourceLink.GitHub" version="1.0.0-beta2-19367-01" />
```

**Comment by pierresprim** [comment]
Following to your request, I made two new releases : a stable release that does not support this beta feature (0.74.3) and a beta release that supports it (0.74.3.1-beta).
